### ISSUE TITLE
JSCPD Failures on Minor Update v6.3.1 --> v6.4.0

### ISSUE THREAD

**Issue by wegmans-alex-beck** [super-linter/super-linter#5541] opened 2024-04-18 14:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JSCPD runs on the entire workspace, even files that have not changed.

### Expected Behavior

Previous Behavior: JSCPD was running only on changed files found with a `git diff`.

### Super-Linter version

```markdown
v6.4.0
```

### Relevant log output

```shell
2024-04-17T13:45:38.8235365Z [0m2024-04-17 13:45:38 [0;34m[DEBUG][0m   Initializing FILE_ARRAY_JSCPD[0m

2024-04-17T13:45:39.0838105Z jscpd: 3.5.10

2024-04-17T13:45:39.4440830Z [0m2024-04-17 13:45:39 [0;34m[DEBUG][0m   Set VALIDATE_LANGUAGE while validating the configuration: VALIDATE_JSCPD[0m
2024-04-17T13:45:39.4482591Z [0m2024-04-17 13:45:39 [0;34m[DEBUG][0m   Configuration didn't provide a custom value for VALIDATE_JSCPD[0m

2024-04-17T13:45:39.8707894Z [0m2024-04-17 13:45:39 [0;34m[DEBUG][0m   - Validating [JSCPD] files in code base...[0m

2024-04-17T13:45:41.2143413Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m   Loading rules for JSCPD...[0m
2024-04-17T13:45:41.2178184Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m   Getting linter rules for JSCPD...[0m
2024-04-17T13:45:41.2211469Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m   Default rules location: /action/lib/.automation...[0m
2024-04-17T13:45:41.2245669Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m   Variable names for language file name: JSCPD_FILE_NAME, language linter rules: JSCPD_LINTER_RULES[0m
2024-04-17T13:45:41.2278811Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m   Initializing LANGUAGE_LINTER_RULES value to an empty string...[0m
2024-04-17T13:45:41.2368178Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m   JSCPD language rule file (.jscpd.json) has .jscpd name and json extension[0m
2024-04-17T13:45:41.2400383Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m   Initializing SECONDARY_FILE_NAME and SECONDARY_LANGUAGE_FILE_PATH...[0m
2024-04-17T13:45:41.2435603Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m   Checking if the user-provided:[.jscpd.json] and exists at:[/github/workspace/.github/linters/.jscpd.json][0m
2024-04-17T13:45:41.2469169Z [0m2024-04-17 13:45:41 [0;34m[INFO][0m   ----------------------------------------------[0m
2024-04-17T13:45:41.2503432Z [0m2024-04-17 13:45:41 [0;34m[INFO][0m   User provided file:[/github/workspace/.github/linters/.jscpd.json] exists, setting rules file...[0m
2024-04-17T13:45:41.2538410Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m     -> Language rules file variable (JSCPD_LINTER_RULES) value is:[/github/workspace/.github/linters/.jscpd.json][0m
2024-04-17T13:45:41.2612877Z [0m2024-04-17 13:45:41 [0;34m[DEBUG][0m     -> JSCPD_LINTER_RULES rules file (/github/workspace/.github/linters/.jscpd.json) exists.[0m

2024-04-17T13:45:43.6799337Z [0m2024-04-17 13:45:43 [0;34m[DEBUG][0m   Add /github/workspace to the list of items to lint with JSCPD[0m

2024-04-17T13:45:43.6914732Z [0m2024-04-17 13:45:43 [0;34m[DEBUG][0m   Add /github/workspace to the list of items to lint with JSCPD[0m

2024-04-17T13:45:43.7029975Z [0m2024-04-17 13:45:43 [0;34m[DEBUG][0m   Add /github/workspace to the list of items to lint with JSCPD[0m

2024-04-17T13:45:52.0168479Z LintCodebase JSCPD "false"


2024-04-17T13:45:52.2898503Z { "Seq": 29, "Host": ":", "Starttime": 1713361545.948, "JobRuntime": 1.742, "Send": 0, "Receive": 6555, "Exitval": 0, "Signal": 0, "Command": "LintCodebase JSCPD \"false\"", "V": [ "JSCPD" ], "Stdout": "[0m2024-04-17 13:45:45 [0;34m[DEBUG][0m   Running LintCodebase. FILE_TYPE: JSCPD. TEST_CASE_RUN: false[0m
2024-04-17T13:45:52.2899252Z [0m2024-04-17 13:45:45 [0;34m[DEBUG][0m   VALIDATE_LANGUAGE for JSCPD: true...[0m
2024-04-17T13:45:52.2899920Z [0m2024-04-17 13:45:45 [0;34m[DEBUG][0m   TEST_CASE_RUN has a valid boolean string value: false[0m
2024-04-17T13:45:52.2900763Z [0m2024-04-17 13:45:45 [0;34m[DEBUG][0m   VALIDATE_JSCPD has a valid boolean string value: true[0m
2024-04-17T13:45:52.2901272Z [0m2024-04-17 13:45:45 [0;34m[DEBUG][0m   Populating file array for JSCPD[0m
2024-04-17T13:45:52.2901950Z [0m2024-04-17 13:45:45 [0;34m[DEBUG][0m   There are 1 items to lint for JSCPD: /github/workspace[0m
2024-04-17T13:45:52.2902392Z ::group::JSCPD
2024-04-17T13:45:52.2902533Z ##[group]JSCPD
2024-04-17T13:45:52.2903103Z [0m2024-04-17 13:45:45 [0;34m[DEBUG][0m   Started GitHub Actions log group: JSCPD[0m
2024-04-17T13:45:52.2903568Z [0m2024-04-17 13:45:45 [0;34m[INFO][0m   Linting JSCPD items...[0m
2024-04-17T13:45:52.2904544Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   PARALLEL_RESULTS_FILE_PATH for JSCPD: /tmp/super-linter-worker-results-JSCPD.json[0m
2024-04-17T13:45:52.2905271Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   LOG_DEBUG is enabled. Enable verbose ouput for parallel[0m
2024-04-17T13:45:52.2906774Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   PARALLEL_COMMAND for JSCPD: parallel --will-cite --keep-order --max-procs 2 --xargs --results /tmp/super-linter-worker-results-JSCPD.json --verbose[0m
2024-04-17T13:45:52.2908053Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   JSCPD doesn't support linting files in batches. Configure the linter to run over the files to lint one by one[0m
2024-04-17T13:45:52.2910168Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   PARALLEL_COMMAND for JSCPD after updating the number of files to lint per process: parallel --will-cite --keep-order --max-procs 2 --xargs --results /tmp/super-linter-worker-results-JSCPD.json --verbose --max-lines 1[0m
2024-04-17T13:45:52.2910859Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   LINTER_WORKING_DIRECTORY for JSCPD: /github/workspace[0m
2024-04-17T13:45:52.2913045Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   PARALLEL_COMMAND for JSCPD after updating the working directory: parallel --will-cite --keep-order --max-procs 2 --xargs --results /tmp/super-linter-worker-results-JSCPD.json --verbose --max-lines 1 --workdir /github/workspace[0m
2024-04-17T13:45:52.2914174Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   Checking if /github/workspace/.github/linters/.checkov.yml contains a 'directory:' configuration option[0m
2024-04-17T13:45:52.2915141Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   /github/workspace/.github/linters/.checkov.yml doesn't contain a 'directory:' statement[0m
2024-04-17T13:45:52.2915825Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   Adding the '--directory' option to the Checkov command.[0m
2024-04-17T13:45:52.2916918Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   LINTER_COMMAND_ARRAY for JSCPD has 3 elements: jscpd --config /github/workspace/.github/linters/.jscpd.json[0m
2024-04-17T13:45:52.2919849Z [0m2024-04-17 13:45:46 [0;34m[DEBUG][0m   PARALLEL_COMMAND for JSCPD after LINTER_COMMAND_ARRAY concatenation: parallel --will-cite --keep-order --max-procs 2 --xargs --results /tmp/super-linter-worker-results-JSCPD.json --verbose --max-lines 1 --workdir /github/workspace jscpd --config /github/workspace/.github/linters/.jscpd.json[0m
2024-04-17T13:45:52.2921418Z [0m2024-04-17 13:45:47 [0;34m[DEBUG][0m   PARALLEL_COMMAND_OUTPUT for JSCPD (exit code: 1): cd /github/workspace || exit 255; jscpd --config /github/workspace/.github/linters/.jscpd.json /github/workspace[0m
2024-04-17T13:45:52.2922377Z [0m2024-04-17 13:45:47 [0;34m[DEBUG][0m   Parallel output file (/tmp/super-linter-worker-results-JSCPD.json) contents for JSCPD:
2024-04-17T13:45:52.2924599Z { \"Seq\": 1, \"Host\": \":\", \"Starttime\": 1713361546.255, \"JobRuntime\": 1.375, \"Send\": 0, \"Receive\": 560, \"Exitval\": 1, \"Signal\": 0, \"Command\": \"jscpd --config /github/workspace/.github/linters/.jscpd.json /github/workspace\", \"V\": [ \"/github/workspace\" ], \"Stdout\": \"Clone found (python):
2024-04-17T13:45:52.2925286Z  - fold/file1.py [1:1 - 13:18] (12 lines, 85 tokens)
2024-04-17T13:45:52.2925783Z    fold/file2.py [1:1 - 13:19]
2024-04-17T13:45:52.2925795Z 
2024-04-17T13:45:52.2925992Z HTML report saved to report/html/
2024-04-17T13:45:52.2926321Z Markdown report saved to report/jscpd-report.md
2024-04-17T13:45:52.2926733Z Error: ERROR: jscpd found too many duplicates (1.75%) over threshold (0%)
2024-04-17T13:45:52.2927323Z     at ThresholdReporter.report (/node_modules/@jscpd/finder/dist/reporters/threshold.js:12:19)
2024-04-17T13:45:52.2927784Z     at /node_modules/@jscpd/finder/dist/in-files-detector.js:82:26
2024-04-17T13:45:52.2927968Z     at Array.forEach (<anonymous>)
2024-04-17T13:45:52.2928400Z     at /node_modules/@jscpd/finder/dist/in-files-detector.js:81:28
2024-04-17T13:45:52.2928852Z \", \"Stderr\": \"ERROR: jscpd found too many duplicates (1.75%) over threshold (0%)
2024-04-17T13:45:52.2929018Z \" }[0m
2024-04-17T13:45:52.2929655Z [0m2024-04-17 13:45:47 [0;31m[ERROR][0m   Found errors when linting JSCPD. Exit code: 1.[0m
2024-04-17T13:45:52.2930096Z [0m2024-04-17 13:45:47 [0;34m[DEBUG][0m   RESULTS_OBJECT for JSCPD:
2024-04-17T13:45:52.2930222Z [
2024-04-17T13:45:52.2930339Z   {
2024-04-17T13:45:52.2930477Z     \"Seq\": 1,
2024-04-17T13:45:52.2930612Z     \"Host\": \":\",
2024-04-17T13:45:52.2930766Z     \"Starttime\": 1713361546.255,
2024-04-17T13:45:52.2930919Z     \"JobRuntime\": 1.375,
2024-04-17T13:45:52.2931055Z     \"Send\": 0,
2024-04-17T13:45:52.2931191Z     \"Receive\": 560,
2024-04-17T13:45:52.2931335Z     \"Exitval\": 1,
2024-04-17T13:45:52.2931472Z     \"Signal\": 0,
2024-04-17T13:45:52.2932173Z     \"Command\": \"jscpd --config /github/workspace/.github/linters/.jscpd.json /github/workspace\",
2024-04-17T13:45:52.2932301Z     \"V\": [
2024-04-17T13:45:52.2932457Z       \"/github/workspace\"
2024-04-17T13:45:52.2932582Z     ],
2024-04-17T13:45:52.2932764Z     \"Stdout\": \"Clone found (python):
2024-04-17T13:45:52.2933209Z  - fold/file1.py [1:1 - 13:18] (12 lines, 85 tokens)
2024-04-17T13:45:52.2933507Z    fold/file2.py [1:1 - 13:19]
2024-04-17T13:45:52.2933522Z 
2024-04-17T13:45:52.2933696Z HTML report saved to report/html/
2024-04-17T13:45:52.2934007Z Markdown report saved to report/jscpd-report.md
2024-04-17T13:45:52.2934405Z Error: ERROR: jscpd found too many duplicates (1.75%) over threshold (0%)
2024-04-17T13:45:52.2934964Z     at ThresholdReporter.report (/node_modules/@jscpd/finder/dist/reporters/threshold.js:12:19)
2024-04-17T13:45:52.2935387Z     at /node_modules/@jscpd/finder/dist/in-files-detector.js:82:26
2024-04-17T13:45:52.2935562Z     at Array.forEach (<anonymous>)
2024-04-17T13:45:52.2935986Z     at /node_modules/@jscpd/finder/dist/in-files-detector.js:81:28
2024-04-17T13:45:52.2936110Z \",
2024-04-17T13:45:52.2936552Z     \"Stderr\": \"ERROR: jscpd found too many duplicates (1.75%) over threshold (0%)
2024-04-17T13:45:52.2936676Z \"
2024-04-17T13:45:52.2936793Z   }
2024-04-17T13:45:52.2936951Z ][0m
2024-04-17T13:45:52.2937424Z [0m2024-04-17 13:45:47 [0;34m[DEBUG][0m   Set INDEX for JSCPD to: 1[0m
2024-04-17T13:45:52.2937859Z [0m2024-04-17 13:45:47 [0;34m[INFO][0m   Command output for JSCPD:
2024-04-17T13:45:52.2938015Z ------
2024-04-17T13:45:52.2938164Z Clone found (python):
2024-04-17T13:45:52.2938597Z  - fold/file1.py [1:1 - 13:18] (12 lines, 85 tokens)
2024-04-17T13:45:52.2938889Z    fold/file2.py [1:1 - 13:19]
2024-04-17T13:45:52.2938898Z 
2024-04-17T13:45:52.2939070Z HTML report saved to report/html/
2024-04-17T13:45:52.2939383Z Markdown report saved to report/jscpd-report.md
2024-04-17T13:45:52.2939780Z Error: ERROR: jscpd found too many duplicates (1.75%) over threshold (0%)
2024-04-17T13:45:52.2940332Z     at ThresholdReporter.report (/node_modules/@jscpd/finder/dist/reporters/threshold.js:12:19)
2024-04-17T13:45:52.2940754Z     at /node_modules/@jscpd/finder/dist/in-files-detector.js:82:26
2024-04-17T13:45:52.2941089Z     at Array.forEach (<anonymous>)
2024-04-17T13:45:52.2941558Z     at /node_modules/@jscpd/finder/dist/in-files-detector.js:81:28
2024-04-17T13:45:52.2941895Z ------[0m
2024-04-17T13:45:52.2942956Z [0m2024-04-17 13:45:47 [0;34m[DEBUG][0m   Saving stdout for JSCPD to /tmp/super-linter-parallel-stdout-JSCPD in case we need it later[0m
2024-04-17T13:45:52.2943418Z [0m2024-04-17 13:45:47 [0;34m[INFO][0m   Stderr contents for JSCPD:
2024-04-17T13:45:52.2943569Z ------
2024-04-17T13:45:52.2943932Z ERROR: jscpd found too many duplicates (1.75%) over threshold (0%)
2024-04-17T13:45:52.2944092Z ------[0m
2024-04-17T13:45:52.2945136Z [0m2024-04-17 13:45:47 [0;34m[DEBUG][0m   Saving stderr for JSCPD to /tmp/super-linter-parallel-stderr-JSCPD in case we need it later[0m
2024-04-17T13:45:52.2945708Z [0m2024-04-17 13:45:47 [0;34m[DEBUG][0m   Ending GitHub Actions log group: JSCPD[0m
2024-04-17T13:45:52.2946146Z ::endgroup::
2024-04-17T13:45:52.2946287Z ##[endgroup]
2024-04-17T13:45:52.2946426Z ", "Stderr": "" }

2024-04-17T13:45:53.5942981Z [0m2024-04-17 13:45:53 [0;34m[DEBUG][0m   ERROR_COUNTER for JSCPD: 1[0m
2024-04-17T13:45:53.5984681Z [0m2024-04-17 13:45:53 [0;31m[ERROR][0m   Errors found in JSCPD[0m
2024-04-17T13:45:53.6021999Z [0m2024-04-17 13:45:53 [0;34m[DEBUG][0m   Calling Multi-Status API for JSCPD with status error[0m
2024-04-17T13:45:54.0489546Z [0m2024-04-17 13:45:54 [0;34m[DEBUG][0m   Setting super-linter exit code to 1 because there were errors for JSCPD[0m
```

### Steps To Reproduce

1. VALIDATE_ALL_CODEBASE: false
2. Upgrade from v6.3.1 to v6.4.0
3. On pull_request workflow executes super-linter

### Anything else?

Our workflow used the major version `uses: super-linter/super-linter@v6`. The minor upgrade to v6.4.0 from v6.3.1 broke our workflow.

My recommendation would be to wait until a major release (v7.0.0) before introducing this type of change.
See change: [buildFileList.sh](https://github.com/super-linter/super-linter/blob/fdd042766f3ce77de83e7ee2494a1cab44dfab49/lib/functions/buildFileList.sh#L119)

Workaround: 
- Adding `jscpd.json` with higher threshold than 0%
- Disable with option `VALIDATE_JSCPD=false`
- Pin GitHub Action to `super-linter/super-linter@v6.3` to no longer receive minor changes

** I suspect `VALIDATE_ALL_CODEBASE: false` is not fully compatible with linters that require the entire GitHub workspace path.

**Comment by ferrarimarco** [comment] 2024-04-18 16:07
Hi @wegmans-alex-beck !

> JSCPD runs on the entire workspace, even files that have not changed.

This is working as intended, as described in the [upgrade guide](https://github.com/super-linter/super-linter/blob/main/docs/upgrade-guide.md#jscpd).

The main reason for this is that the way super-linter <= `v5` invoked Jscpd was about scanning files one by one, and it was looking for duplicates within each file, not across all the files that changed. This was perhaps of limited usability, and surprising for some users.

> I suspect VALIDATE_ALL_CODEBASE: false is not fully compatible with linters that require the entire GitHub workspace path.

You're correct. Another example is `ansible-lint`.  `Checkov` may be, to some extent, but it's a bit different because you can still limit its scope with configuration.

> Our workflow used the major version uses: super-linter/super-linter@v6. The minor upgrade to v6.4.0 from v6.3.1 broke our workflow.

I'm surprised by the fact that this upgrade broke your workflow because this behavior was implemented in `v6.0.0`.

Considering this, I'm going to close this because it's not actually a bug.

**Closed by ferrarimarco** 2024-04-18 16:07 UTC
Labels: bug

**Comment by wegmans-alex-beck** [comment] 2024-04-19 17:42
Hi @ferrarimarco !

> I'm surprised by the fact that this upgrade broke your workflow because this behavior was implemented in `v6.0.0`.

I had another repository with the same issue today. I took this chance to debug it further.
Here is what I found.

- v6.3.1
```
2024-04-19T16:08:58.3975643Z [0m2024-04-19 16:08:58 [0;34m[DEBUG][0m   /github/workspace matches with /github/workspace. Adding it to the list of directories to lint for linters that are expected to lint the whole codebase[0m
2024-04-19T16:08:58.3978337Z [0m2024-04-19 16:08:58 [0;34m[DEBUG][0m   Checking if /github/workspace/.github/linters/.checkov.yml contains a 'directory:' configuration option[0m
2024-04-19T16:08:58.3980558Z [0m2024-04-19 16:08:58 [0;34m[DEBUG][0m   /github/workspace/.github/linters/.checkov.yml doesn't contain a 'directory:' statement[0m
2024-04-19T16:08:58.3982566Z [0m2024-04-19 16:08:58 [0;34m[DEBUG][0m   Adding /github/workspace to the list of directories to analyze with Checkov.[0m
2024-04-19T16:08:58.3983749Z ", "Stderr": "" }[0m
```

- v6.4.0
```
2024-04-19T16:03:25.3570468Z [0m2024-04-19 16:03:25 [0;34m[DEBUG][0m   /github/workspace matches with /github/workspace. Adding it to the list of directories to lint for linters that are expected to lint the whole codebase[0m
2024-04-19T16:03:25.3573156Z [0m2024-04-19 16:03:25 [0;34m[DEBUG][0m   Checking if /github/workspace/.github/linters/.checkov.yml contains a 'directory:' configuration option[0m
2024-04-19T16:03:25.3575372Z [0m2024-04-19 16:03:25 [0;34m[DEBUG][0m   /github/workspace/.github/linters/.checkov.yml doesn't contain a 'directory:' statement[0m
2024-04-19T16:03:25.3577310Z [0m2024-04-19 16:03:25 [0;34m[DEBUG][0m   Adding /github/workspace to the list of directories to analyze with Checkov.[0m
2024-04-19T16:03:25.3579028Z [0m2024-04-19 16:03:25 [0;34m[DEBUG][0m   Add /github/workspace to the list of items to lint with JSCPD[0m
2024-04-19T16:03:25.3580093Z ", "Stderr": "" }[0m
```

I believe it was these two sections of code interacting with each other.
[linter.sh](https://github.com/super-linter/super-linter/blob/cb109f45f142b31b9c5e4796dbba383f662e1ff7/lib/linter.sh#L96)
[buildFileList.sh](https://github.com/super-linter/super-linter/blob/bd56ae560840642eb0b558c5febecc28d2e8401d/lib/functions/buildFileList.sh#L244)

Thank you for looking into this! I agree that this can be closed.

**Comment by grahame-student** [comment] 2024-08-27 11:34
Not wanting to be a necromancer, but a more useful behaviour might be to analyse all files in the work area but **only** report on the files modified in relation to the branch specified in the `DEFAULT_BRANCH:` key.

Not sure if the super-linter infrastructure supports this more nuanced reporting method.

**Comment by ferrarimarco** [comment] 2024-08-27 18:57
@grahame-student Super-linter supports this, but Jscpd does not, AFAIK.
