### ISSUE TITLE
jscpd looks for code duplicate in images

### ISSUE THREAD

**Issue by fungiboletus** [super-linter/super-linter#3966] opened 2023-03-01 18:14 UTC
## Describe the bug

jscpd looks for code duplicate in images, which takes some time with very little chances to find duplicates.

## Expected behavior

Perhaps filenames with extensions from common binary files should be ignored by jscpd by default.

**Comment by nvuillam** [comment] 2023-03-01 21:12
Agreed :o :o 
I'll make a PR to add JPG PNG & SVG extensions to the default .jscpd.json shipped with MegaLinter !

**Comment by nvuillam** [comment] 2023-03-01 21:12
oops sorry wrong repo ^^
I'm sure anyone can easily do the same i super-linter :)

**Comment by fungiboletus** [comment] 2023-04-01 20:20
.

**Comment by fungiboletus** [comment] 2023-05-02 08:28
.

**Comment by fungiboletus** [comment] 2023-06-02 12:56
.

**Comment by fungiboletus** [comment] 2023-07-04 08:59
yo

**Comment by ferrarimarco** [comment] 2023-12-12 17:02
@fungiboletus Hi! Thanks for this report.

Can you please share more about how you're running and configuring super-linter, so we can reproduce this?

**Comment by fungiboletus** [comment] 2023-12-12 18:21
I believe I used the default configuration from the getting started section in the readme at the time of the issue. My repository had some images in it.

**Comment by ferrarimarco** [comment] 2023-12-13 09:51
Thanks for following up. For now, I'm going to close this because we don't have a reproduction case.

**Comment by fungiboletus** [comment] 2023-12-13 11:02
Here you go: https://github.com/fungiboletus/superlint-jscpd-images

It's an example repository with an image and the default configuration from the getting started section in the readme.

The .webp image is processed by jscpd (and also gitleaks and textlint).

![image](https://github.com/super-linter/super-linter/assets/45740/a2627089-cb33-4313-a8e8-dc54945356ac)

**Comment by ferrarimarco** [comment] 2023-12-14 11:58
@fungiboletus thanks for this example.

I think this is a fair request. We should exclude at least the same files we exclude when using `find`:

https://github.com/super-linter/super-linter/blob/b9d7d8d9ab1981d12baa737605e43f52e1b501da/lib/functions/buildFileList.sh#L111-L131

**Comment by ferrarimarco** [comment] 2023-12-27 11:48
Given the changes in #5041, this should be solved.

**Closed by ferrarimarco** 2023-12-27 11:48 UTC
Labels: enhancement, O: backlog 🤖
