### ISSUE TITLE
Seeing "error: failed to fetch latest version for terraform provider" since super-linter 4.10.0

### ISSUE THREAD

**Issue by hajapy** [super-linter/super-linter#4000] opened 2023-03-13 20:22 UTC
## Describe the bug

Since updating super-linter for v4.10.0, scanning terraform via super-linter emits messages like:

```
error   commons/terraform-provider.go:112       failed to fetch latest version for terraform provider, error: error preparing the providers list endpoint, error: hostname can't be empty
```

which wasn't appearing in super-linter 4.9.7, using terrascan 1.15.2. I traced this back to https://github.com/tenable/terrascan/blob/e4a4aec1776049cdede0457fa91a8e88be8e3499/pkg/iac-providers/terraform/commons/terraform-provider.go#L112 which was added in 1.17.1. 

## Expected behavior

There should be no error messages like this in the scan output.

## Steps to Reproduce
I can reproduce this in a minimal example. Put these two files in a folder

```bash
❯ cat main.tf
terraform {
  required_version = ">= 1.0, < 2.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.15.1, < 5.0.0"
    }
  }
}

provider "aws" {
}
❯ cat resources.tf
resource "aws_ssm_parameter" "example" {
  name  = "/example/param"
  value = "example"
}
```

Now run:

```bash
❯ docker run --rm -it -v "$(pwd):/iac" -w /iac tenable/terrascan:1.17.1 scan -i terraform -f resources.tf
```

and see output:
```
2023-01-13T17:18:25.896Z	error	commons/terraform-provider.go:112	failed to fetch latest version for terraform provider, error: error preparing the providers list endpoint, error: hostname can't be empty

Scan Summary -

	File/Folder         :	/iac/resources.tf
	IaC Type            :	terraform
	Scanned At          :	2023-01-13 17:18:32.931563921 +0000 UTC
	Policies Validated  :	0
	Violated Policies   :	0
	Low                 :	0
	Medium              :	0
	High                :	0
```

In 1.17.0, this error doesn't appear:

```bash
❯ docker run --rm -it -v "$(pwd):/iac" -w /iac tenable/terrascan:1.17.0 scan -i terraform -f resources.tf

Scan Summary -

	File/Folder         :	/iac/resources.tf
	IaC Type            :	terraform
	Scanned At          :	2023-01-13 17:22:50.002319846 +0000 UTC
	Policies Validated  :	0
	Violated Policies   :	0
	Low                 :	0
	Medium              :	0
	High                :	0
```

In 1.17.1, if I omit the -f flag giving it the individual file that lacks a terraform provider block, there is no problem. I think super-linter runs file-by-file so I believe that could be the reason the required provider cannot be seen when scanning the `resources.tf` file. 

## Additional context

I believe this may be due to the file-by-file nature of scanning that super-linter does. I think terrascan needs to scan a whole directory at a time rather than a file at a time. 

X-ref issue in terrascan repo: https://github.com/tenable/terrascan/issues/1512

**Comment by hajapy** [comment] 2023-04-13 02:23
This issue is not resolved

**Comment by hajapy** [comment] 2023-05-21 14:02
This error is still present for super-linter v5.0.0.

Reproduction steps:

```bash
mkdir bug
cd bug
git init

cat <<EOT >> main.tf
terraform {
  required_version = ">= 1.0, < 2.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.15.1, < 5.0.0"
    }
  }
}

provider "aws" {
}
EOT

cat <<EOT >> resources.tf
resource "aws_ssm_parameter" "example" {
  name  = "/example/param"
  value = "example"
}
EOT

git add *.tf
git commit -m "init"

docker run --rm \
  -e RUN_LOCAL=true \
  -e ACTIONS_RUNNER_DEBUG=true \
  -e DISABLE_ERRORS=false \
  -e ERROR_ON_MISSING_EXEC_BIT=true \
  -e LINTER_RULES_PATH=. \
  -e MULTI_STATUS=false \
  -e VALIDATE_ALL_CODEBASE=true \
  -e CREATE_LOG_FILE=true \
  -v $(pwd):/tmp/lint \
  -w /tmp/lint \
  ghcr.io/github/super-linter:slim-v5.0.0
```

This generates the attached log file: 
[super-linter.log](https://github.com/super-linter/super-linter/files/11524704/super-linter.log)


with relevant portion:

```
2023-05-21 13:56:16 [DEBUG]   Linting FILE: /tmp/lint/resources.tf
2023-05-21 13:56:16 [DEBUG]   FILE_STATUS (resources.tf) is empty, or not set to 'good' or 'bad'. Assuming it should be linted correctly. Setting FILE_STATUS to 'good'...
2023-05-21 13:56:16 [DEBUG]   File: /tmp/lint/resources.tf, FILE_NAME: resources.tf, DIR_NAME:/tmp/lint, FILE_STATUS: good, INDIVIDUAL_TEST_FOLDER: terraform_terrascan, TEST_CASE_DIRECTORY: .automation/test/terraform_terrascan
2023-05-21 13:56:16 [DEBUG]   TERRAFORM_TERRASCAN expects to lint individual files. Updated TEST_CASE_DIRECTORY to: .automation/test/terraform_terrascan/
2023-05-21 13:56:16 [INFO]   ---------------------------
2023-05-21 13:56:16 [INFO]   File:[/tmp/lint/resources.tf]
2023-05-21 13:56:23 [INFO]    - File:[resources.tf] was linted with [terrascan] successfully
2023-05-21 13:56:23 [INFO]      - Command output:
------
2023-05-21T13:56:17.040Z        error   commons/terraform-provider.go:112       failed to fetch latest version for terraform provider, error: error preparing the providers list endpoint, error: hostname can't be empty



Scan Summary -

        File/Folder         :   /tmp/lint/resources.tf
        IaC Type            :   terraform
        Scanned At          :   2023-05-21 13:56:23.78801943 +0000 UTC
        Policies Validated  :   0
        Violated Policies   :   0
        Low                 :   0
        Medium              :   0
        High                :   0

------
2023-05-21 13:56:23 [DEBUG]   Error code: 0. Command output:
------
2023-05-21T13:56:17.040Z        error   commons/terraform-provider.go:112       failed to fetch latest version for terraform provider, error: error preparing the providers list endpoint, error: hostname can't be empty



Scan Summary -

        File/Folder         :   /tmp/lint/resources.tf
        IaC Type            :   terraform
        Scanned At          :   2023-05-21 13:56:23.78801943 +0000 UTC
        Policies Validated  :   0
        Violated Policies   :   0
        Low                 :   0
        Medium              :   0
        High                :   0

------
```

**Comment by hajapy** [comment] 2023-05-21 14:04
`TERRAFORM_TERRASCAN expects to lint individual files.` seems like the main issue to me. I think terrascan needs to scan the whole directory in one pass in order to understand the provider declared in a separate tf file.

**Comment by Hanse00** [comment] 2023-05-24 00:21
Hey @hajapy, thanks for the report. I'm applying the backlog label to stop stalebot from marking this as stale for you. We'll have to get around to reviewing this sometime soon. Thanks!

**Comment by mcaulifn** [comment] 2023-11-27 16:33
Any update on this?

**Comment by ferrarimarco** [comment] 2023-12-27 11:44
Hi folks! Can you please help us reproduce this issue with the latest super-linter release, so we can investigate? Thanks!

**Comment by ferrarimarco** [comment] 2023-12-27 11:46
From what I see in your first message, it seems to be related to Terrascan, rather than to super-linter? I would suggest reporting this in their issue tracker.

**Comment by dark-vex** [comment] 2023-12-27 21:19
Hey Marco, I think this has been fixed on Terrascan side, I'm unable to reproduce with Terrascan image 1.18.11 (which is the same used by super-linter):
https://github.com/tenable/terrascan/issues/1512#issuecomment-1870630435
I was having the same issue of the author earlier, so I guess this can be marked as resolved?

**Comment by ferrarimarco** [comment] 2023-12-27 22:45
Thanks for following up!

**Closed by ferrarimarco** 2023-12-27 22:45 UTC
Labels: bug, good first issue
