### ISSUE TITLE
JAVASCRIPT_ES: Invalid option '--eslintrc' - perhaps you meant '--ignore'?

### ISSUE THREAD

**Issue by patricklubach** [super-linter/super-linter#5808] opened 2024-07-01 10:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

When running super-linter through Github Actions or locally using the super-linter container image I receive always the same error for JAVASCRIPT_ES and JSON linter:
`Invalid option '--eslintrc' - perhaps you meant '--ignore'?
  You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.`

### Expected Behavior

super-linter lints the codebase successfully and returns with exit code 0.

### Super-Linter version

```markdown
v6 / v6.6.0
```

### Relevant log output

```shell
I prepared a Github Action run with v6 here - link points to the error:
https://github.com/patricklubach/approver-action/actions/runs/9742603873/job/26884239041#step:8:5498

And one for v6.6.0 here - link points to the error:
https://github.com/patricklubach/approver-action/actions/runs/9742742949/job/26884666606#step:8:5498
```

### Steps To Reproduce

The same error appears locally when running super-linter using docker:

1. Clone repository: https://github.com/patricklubach/approver-action
2. Switch into cloned repository.
3. Run docker command: 

```bash
docker run \
  -e LOG_LEVEL=DEBUG \
  -e DEFAULT_BRANCH=main \
  -e JAVASCRIPT_DEFAULT_STYLE=prettier \
  -e VALIDATE_ALL_CODEBASE=true \
  -e VALIDATE_JSCPD=false \
  -e CREATE_LOG_FILE=true \
  --rm \
  -e RUN_LOCAL=true \
  -v $PWD:/tmp/lint \
  ghcr.io/super-linter/super-linter:v6.6.0
```

4. Optional: May you need to change permissions on the `super-linter.log` file: `sudo chmod o+r super-linter.log`

### Anything else?

**Context:**

Currently I am learning JavaScript and try to create my first Github Action and used the template here: https://github.com/actions/javascript-action/tree/main

Link to my repository: https://github.com/patricklubach/approver-action

If you need something, let me know.

**Comment by ferrarimarco** [comment] 2024-07-01 11:55
Hi @patricklubach ! I think this is a duplicate of #5688.

**Closed by ferrarimarco** 2024-07-01 11:55 UTC
Labels: bug

**Comment by patricklubach** [comment] 2024-07-01 12:56
@ferrarimarco thank you for replying. As it was pointed out in the issue you referenced it is more a feature request than a bug so maybe I didn't see it but anyway I will test the fix later today and if it works I will close this one and follow up on the other one. Thank you very much!
