### ISSUE TITLE
super-linter v6+ JSON validation fails with eslint error

### ISSUE THREAD

**Issue by megamorf** [super-linter/super-linter#6293] opened 2024-10-21 14:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

We have a FE project where the super-linter is configured with `VALIDATE_JSON: true` - however when run the JSON validation fails with an eslint error:

```plaintext
Oops! Something went wrong! :(
  
  ESLint: 8.57.0
  
  Error: Cannot read config file: /github/workspace/packages/config-generator/.eslintrc.cjs
  Error: Cannot find module '@rushstack/eslint-patch/modern-module-resolution'
  Require stack:
  - /github/workspace/packages/config-generator/.eslintrc.cjs
  - /node_modules/@eslint/eslintrc/dist/eslintrc.cjs
  - /node_modules/eslint/lib/cli-engine/cli-engine.js
  - /node_modules/eslint/lib/eslint/eslint.js
  - /node_modules/eslint/lib/eslint/index.js
  - /node_modules/eslint/lib/cli.js
  - /node_modules/eslint/bin/eslint.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
      at Module._load (node:internal/modules/cjs/loader:983:27)
      at Module.require (node:internal/modules/cjs/loader:1230:19)
      at require (node:internal/modules/helpers:179:18)
      at Object.<anonymous> (/github/workspace/packages/config-generator/.eslintrc.cjs:1:1)
      at Module._compile (node:internal/modules/cjs/loader:1368:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
      at Module.load (node:internal/modules/cjs/loader:1205:32)
      at Module._load (node:internal/modules/cjs/loader:1021:12)
      at Module.require (node:internal/modules/cjs/loader:1230:19)
```

In our case we suspect this is caused by the following eslint config: `packages/config-generator/.eslintrc.cjs`

```javascript
require('@rushstack/eslint-patch/modern-module-resolution');

module.exports = {};
```

Similar issues have been reported here:
- #4964
- https://github.com/super-linter/super-linter/issues/6089#issuecomment-2318705741

### Expected Behavior

The validation of JSON files finishes successfully.

Is there a way that we can have the super-linter validate JSON files without requiring external dependencies? Normally we use it standalone as shown in the workflow snippet below.

### Super-Linter version

```markdown
super-linter/super-linter:slim-v7.1.0
```

### Super-linter configuration

```yaml
jobs:
  lint:
    runs-on: [contoso-small-x86-spot]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter/slim@v7
        env:
          GITHUB_CUSTOM_API_URL: ${{ github.api_url }}
          GITHUB_CUSTOM_SERVER_URL: ${{ github.server_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint.yaml
          FILTER_REGEX_EXCLUDE: (CHANGELOG|PULL_REQUEST_TEMPLATE|LICENSE).md|configs\/.*
```

### Relevant log output

```plaintext
2024-10-16T10:33:47.5828125Z ##[group]Run super-linter/super-linter/slim@v7
2024-10-16T10:33:47.5828878Z env:
2024-10-16T10:33:47.5829394Z   GITHUB_CUSTOM_API_URL: https://git.contoso.com/api/v3
2024-10-16T10:33:47.5830147Z   GITHUB_CUSTOM_SERVER_URL: https://git.contoso.com
2024-10-16T10:33:47.5831224Z   GITHUB_TOKEN: ***
2024-10-16T10:33:47.5831653Z   LINTER_RULES_PATH: /
2024-10-16T10:33:47.5832334Z   MARKDOWN_CONFIG_FILE: .markdownlint.yaml
2024-10-16T10:33:47.5832896Z   VALIDATE_GITHUB_ACTIONS: true
2024-10-16T10:33:47.5833361Z   VALIDATE_JSON: true
2024-10-16T10:33:47.5833877Z   VALIDATE_MARKDOWN: true
2024-10-16T10:33:47.5834322Z   VALIDATE_YAML: true
2024-10-16T10:33:47.5834811Z   YAML_CONFIG_FILE: .yamllint.yaml
2024-10-16T10:33:47.5835557Z   FILTER_REGEX_EXCLUDE: (CHANGELOG|PULL_REQUEST_TEMPLATE|LICENSE).md|configs\/.*
2024-10-16T10:33:47.5836240Z ##[endgroup]
2024-10-16T10:33:47.6075297Z ##[command]/usr/bin/docker run --name ghcriosuperlintersuperlinterslimv710_565923 --label e639ea --workdir /github/workspace --rm -e "GITHUB_CUSTOM_API_URL" -e "GITHUB_CUSTOM_SERVER_URL" -e "GITHUB_TOKEN" -e "LINTER_RULES_PATH" -e "MARKDOWN_CONFIG_FILE" -e "VALIDATE_GITHUB_ACTIONS" -e "VALIDATE_JSON" -e "VALIDATE_MARKDOWN" -e "VALIDATE_YAML" -e "YAML_CONFIG_FILE" -e "FILTER_REGEX_EXCLUDE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/_work/_temp/_github_home":"/github/home" -v "/home/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/_work/some-product-configuration/some-product-configuration":"/github/workspace" ghcr.io/super-linter/super-linter:slim-v7.1.0
2024-10-16T10:33:48.6914173Z ##[group]Super-Linter initialization
2024-10-16T10:33:48.8773493Z 2024-10-16 10:33:48 [INFO]   --------------------------------------------------------------------------------
2024-10-16T10:33:48.8774483Z 
2024-10-16T10:33:48.8774798Z                               /@@#///////@@/(@//@%/(@.@(       @@
2024-10-16T10:33:48.8775514Z                           @@//////////////////////////////#*  @@@
2024-10-16T10:33:48.8776281Z                         @////@//(///////////@@@@@///@//@/@**//@@(
2024-10-16T10:33:48.8777192Z                       @///////@///////////////@@@@    (           @,
2024-10-16T10:33:48.8777925Z                      @/(&/@////////////////////                     @
2024-10-16T10:33:48.8778717Z                     @////////////////////////@@                      @
2024-10-16T10:33:48.8779482Z                   @%////////(//////////%/////&@            @@       *,@           ______________
2024-10-16T10:33:48.8780342Z              @@@@@/@/#/////(&//////////////////                       .@         /              \
2024-10-16T10:33:48.8781387Z         *@@@@@.    .%///(//@//////////////////&.   .@@,                 @%      / Don't mind me  \
2024-10-16T10:33:48.8783035Z       @@%           .&@&&/@.@//&/////(//////////    @@@@@@@@@         .. &@    / I'm just looking \
2024-10-16T10:33:48.8784231Z     @@%               @@@@@   @&/////////////////#   @/       V  @@/ ,@@@ @   <  for some trash... |
2024-10-16T10:33:48.8785182Z @@@%                   @@@@        .%@@@@//////#@ @   @@         @     .,.     \__________________/
2024-10-16T10:33:48.8786045Z                                           @@@/@(  (@@@@% @/\      %
2024-10-16T10:33:48.8787002Z                                            @@@@(    .     .@@/\   #
2024-10-16T10:33:48.8787836Z                                              @                  %@%
2024-10-16T10:33:48.8788327Z 
2024-10-16T10:33:48.8788862Z --------------------------------------------------------------------------------
2024-10-16T10:33:48.8818358Z 2024-10-16 10:33:48 [INFO]   ---------------------------------------------
2024-10-16T10:33:48.8866352Z 2024-10-16 10:33:48 [INFO]   --- GitHub Actions Multi Language Linter ----
2024-10-16T10:33:48.8912896Z 2024-10-16 10:33:48 [INFO]    - Image Creation Date: 2024-08-28T08:07:20Z
2024-10-16T10:33:48.8960997Z 2024-10-16 10:33:48 [INFO]    - Image Revision: b92721f792f381cedc002ecdbb9847a15ece5bb8
2024-10-16T10:33:48.9004842Z 2024-10-16 10:33:48 [INFO]    - Image Version: 7.1.0
2024-10-16T10:33:48.9055726Z 2024-10-16 10:33:48 [INFO]   ---------------------------------------------
2024-10-16T10:33:48.9107368Z 2024-10-16 10:33:48 [INFO]   ---------------------------------------------
2024-10-16T10:33:48.9156040Z 2024-10-16 10:33:48 [INFO]   The Super-Linter source code can be found at:
2024-10-16T10:33:48.9210453Z 2024-10-16 10:33:48 [INFO]    - https://github.com/super-linter/super-linter
2024-10-16T10:33:48.9264231Z 2024-10-16 10:33:48 [INFO]   ---------------------------------------------
2024-10-16T10:33:48.9318673Z 2024-10-16 10:33:48 [INFO]   - Validating all files in code base...
2024-10-16T10:33:49.0106349Z 2024-10-16 10:33:49 [INFO]   chktex: chktex: WARNING -- Could not find global resource file.
2024-10-16T10:33:49.0107590Z ChkTeX v1.7.9 - Copyright 1995-96 Jens T. Berger Thielemann.
2024-10-16T10:33:49.0108583Z Compiled with POSIX extended regex support.
2024-10-16T10:33:49.0109274Z rubocop: 1.65.1
2024-10-16T10:33:49.0110151Z perl: 
2024-10-16T10:33:49.0111156Z This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-thread-multi
2024-10-16T10:33:49.0111873Z 
2024-10-16T10:33:49.0112197Z Copyright 1987-2023, Larry Wall
2024-10-16T10:33:49.0112743Z 
2024-10-16T10:33:49.0113251Z Perl may be copied only under the terms of either the Artistic License or the
2024-10-16T10:33:49.0114307Z GNU General Public License, which may be found in the Perl 5 source kit.
2024-10-16T10:33:49.0114943Z 
2024-10-16T10:33:49.0115392Z Complete documentation for Perl, including FAQ lists, should be found on
2024-10-16T10:33:49.0116478Z this system using "man perl" or "perldoc perl".  If you have access to the
2024-10-16T10:33:49.0117538Z Internet, point your browser at https://www.perl.org/, the Perl Home Page.
2024-10-16T10:33:49.0118463Z xmllint: xmllint: using libxml version 21207
2024-10-16T10:33:49.0120041Z    compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 HTTP DTDValid HTML C14N Catalog XPath XPointer XInclude Iconv ISO8859X Unicode Regexps Automata Schemas Schematron Modules Debug Zlib Lzma 
2024-10-16T10:33:49.0122274Z ansible-lint: ansible-lint 24.7.0 using ansible-core:2.17.3 ansible-compat:24.8.0 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8
2024-10-16T10:33:49.0123505Z eslint: v8.57.0
2024-10-16T10:33:49.0124031Z markdownlint: 0.41.0
2024-10-16T10:33:49.0124696Z snakefmt: snakefmt, version 0.10.2
2024-10-16T10:33:49.0125436Z cpplint: Cpplint fork (https://github.com/cpplint/cpplint)
2024-10-16T10:33:49.0126154Z cpplint 1.6.1
2024-10-16T10:33:49.0126899Z Python 3.12.5 (main, Aug  7 2024, 19:15:55) [GCC 13.2.1 20240309]
2024-10-16T10:33:49.0127778Z editorconfig-checker: v3.0.3
2024-10-16T10:33:49.0128378Z gitleaks: v8.18.4
2024-10-16T10:33:49.0129135Z phpstan: PHPStan - PHP Static Analysis Tool 1.11.2
2024-10-16T10:33:49.0129885Z dotenv-linter: dotenv-linter 3.3.0
2024-10-16T10:33:49.0131027Z asl-validator: 3.8.3
2024-10-16T10:33:49.0131614Z actionlint: 1.7.1
2024-10-16T10:33:49.0132172Z installed by building from source
2024-10-16T10:33:49.0132962Z built with go1.22.3 compiler for linux/amd64
2024-10-16T10:33:49.0133691Z tekton-lint: 1.1.0
2024-10-16T10:33:49.0134224Z terrascan: version: v1.19.1
2024-10-16T10:33:49.0134951Z terraform: Terraform v1.9.5
2024-10-16T10:33:49.0135537Z on linux_amd64
2024-10-16T10:33:49.0136539Z 2024/08/27 15:44:56 traces export: Post "http:///dev/otel-grpc.sock": http: no Host in request URL
2024-10-16T10:33:49.0138019Z 2024/08/27 15:44:56 traces export: Post "http:///dev/otel-grpc.sock": http: no Host in request URL
2024-10-16T10:33:49.0139238Z R: R version 4.4.0 (2024-04-24) -- "Puppy Cup"
2024-10-16T10:33:49.0140182Z Copyright (C) 2024 The R Foundation for Statistical Computing
2024-10-16T10:33:49.0141021Z Platform: x86_64-pc-linux-musl
2024-10-16T10:33:49.0141425Z 
2024-10-16T10:33:49.0141946Z R is free software and comes with ABSOLUTELY NO WARRANTY.
2024-10-16T10:33:49.0143191Z You are welcome to redistribute it under the terms of the
2024-10-16T10:33:49.0144154Z GNU General Public License versions 2 or 3.
2024-10-16T10:33:49.0144999Z For more information about these matters see
2024-10-16T10:33:49.0145779Z https://www.gnu.org/licenses/.
2024-10-16T10:33:49.0146532Z shellcheck: ShellCheck - shell script analysis tool
2024-10-16T10:33:49.0147290Z version: 0.10.0
2024-10-16T10:33:49.0148296Z license: GNU General Public License, version 3
2024-10-16T10:33:49.0149205Z website: https://www.shellcheck.net
2024-10-16T10:33:49.0149914Z jscpd: 4.0.5
2024-10-16T10:33:49.0150437Z black: black, 24.8.0 (compiled: no)
2024-10-16T10:33:49.0151257Z Python (CPython) 3.12.5
2024-10-16T10:33:49.0151807Z prettier: 3.3.3
2024-10-16T10:33:49.0152571Z php: PHP 8.3.10 (cli) (built: Aug  1 2024 20:18:40) (NTS)
2024-10-16T10:33:49.0153749Z Copyright (c) The PHP Group
2024-10-16T10:33:49.0154429Z Zend Engine v4.3.10, Copyright (c) Zend Technologies
2024-10-16T10:33:49.0155271Z textlint: v14.2.0
2024-10-16T10:33:49.0156287Z npm-groovy-lint: GroovyLint: Successfully processed CodeNarc: 
2024-10-16T10:33:49.0157153Z CodeNarc version 3.3.0
2024-10-16T10:33:49.0158119Z npm-groovy-lint version 14.6.0
2024-10-16T10:33:49.0158639Z 
2024-10-16T10:33:49.0159002Z Embeds:
2024-10-16T10:33:49.0159535Z CodeNarc version 3.3.0
2024-10-16T10:33:49.0160339Z - Groovy version 3.0.9 (superlite)
2024-10-16T10:33:49.0162441Z renovate-config-validator: (node:210) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2024-10-16T10:33:49.0164988Z (Use `node --trace-deprecation ...` to show where the warning was created)
2024-10-16T10:33:49.0165938Z 38.55.1
2024-10-16T10:33:49.0167236Z golangci-lint: golangci-lint has version 1.60.3 built with go1.23.0 from c2e095c0 on 2024-08-22T21:51:56Z
2024-10-16T10:33:49.0168363Z ruff: ruff 0.6.2
2024-10-16T10:33:49.0169142Z kubeconform: v0.6.7
2024-10-16T10:33:49.0170268Z golangci-lint: golangci-lint has version 1.60.3 built with go1.23.0 from c2e095c0 on 2024-08-22T21:51:56Z
2024-10-16T10:33:49.0171376Z gherkin-lint: Version command not supported
2024-10-16T10:33:49.0172064Z eslint: v8.57.0
2024-10-16T10:33:49.0172697Z scalafmt: scalafmt 3.8.3
2024-10-16T10:33:49.0173275Z stylelint: 15.11.0
2024-10-16T10:33:49.0173870Z sqlfluff: sqlfluff, version 3.1.1
2024-10-16T10:33:49.0174736Z bash-exec: Version command not supported
2024-10-16T10:33:49.0175599Z google-java-format: google-java-format: Version 1.23.0
2024-10-16T10:33:49.0176594Z phpcs: PHP_CodeSniffer version 3.10.1 (stable) by Squiz and PHPCSStandards
2024-10-16T10:33:49.0177559Z terragrunt: terragrunt version v0.66.9
2024-10-16T10:33:49.0178381Z psalm: Psalm 5.24.0@462c80e31c34e58cc4f750c656be3927e80e550e
2024-10-16T10:33:49.0179214Z pylint: pylint 3.2.6
2024-10-16T10:33:49.0179780Z astroid 3.2.4
2024-10-16T10:33:49.0180423Z Python 3.12.5 (main, Aug  7 2024, 19:15:55) [GCC 13.2.1 20240309]
2024-10-16T10:33:49.0181241Z shfmt: v3.9.0
2024-10-16T10:33:49.0182138Z snakemake: 8.18.2
2024-10-16T10:33:49.0182886Z mypy: mypy 1.11.2 (compiled: yes)
2024-10-16T10:33:49.0183523Z eslint: v8.57.0
2024-10-16T10:33:49.0184044Z coffeelint: 5.2.11
2024-10-16T10:33:49.0184701Z tflint: TFLint version 0.53.0
2024-10-16T10:33:49.0185401Z + ruleset.terraform (0.9.1-bundled)
2024-10-16T10:33:49.0186086Z cfn-lint: cfn-lint 1.10.3
2024-10-16T10:33:49.0187004Z flake8: 7.1.1 (mccabe: 0.7.0, pycodestyle: 2.12.1, pyflakes: 3.2.0) CPython 3.12.5 on
2024-10-16T10:33:49.0187847Z Linux
2024-10-16T10:33:49.0188344Z spectral: 6.11.1
2024-10-16T10:33:49.0188976Z clj-kondo: clj-kondo v2024.08.01
2024-10-16T10:33:49.0189584Z eslint: v8.57.0
2024-10-16T10:33:49.0190323Z ts-standard: 12.0.2
2024-10-16T10:33:49.0190959Z eslint: v8.57.0
2024-10-16T10:33:49.0191575Z protolint: protolint version 0.50.5(6cc254e)
2024-10-16T10:33:49.0192357Z pyink: pyink, 24.3.0 (compiled: no)
2024-10-16T10:33:49.0193031Z Python (CPython) 3.12.5
2024-10-16T10:33:49.0194265Z raku: Welcome to Rakudo™ v2024.04.
2024-10-16T10:33:49.0195139Z Implementing the Raku® Programming Language v6.d.
2024-10-16T10:33:49.0196104Z Built on MoarVM version 2024.04.
2024-10-16T10:33:49.0196886Z prettier: 3.3.3
2024-10-16T10:33:49.0197473Z hadolint: Haskell Dockerfile Linter 2.12.0
2024-10-16T10:33:49.0198356Z checkstyle: Checkstyle version: 10.18.0
2024-10-16T10:33:49.0199773Z clang-format: clang-format version 17.0.6 (https://github.com/llvm/llvm-project.git 6009708b4367171ccdbf4b5905cb6a803753fe18)
2024-10-16T10:33:49.0201250Z ktlint: ktlint version 1.3.1
2024-10-16T10:33:49.0201950Z yamllint: yamllint 1.35.1
2024-10-16T10:33:49.0202768Z dart: Dart SDK version: 3.5.1 (stable) (Tue Aug 13 21:02:17 2024 +0000) on "linux_x64"
2024-10-16T10:33:49.0203630Z isort: 
2024-10-16T10:33:49.0204221Z                  _                 _
2024-10-16T10:33:49.0204865Z                 (_) ___  ___  _ __| |_
2024-10-16T10:33:49.0205650Z                 | |/ _/ / _ \/ '__  _/
2024-10-16T10:33:49.0206444Z                 | |\__ \/\_\/| |  | |_
2024-10-16T10:33:49.0207303Z                 |_|\___/\___/\_/   \_/
2024-10-16T10:33:49.0207728Z 
2024-10-16T10:33:49.0208368Z       isort your imports, so you don't have to.
2024-10-16T10:33:49.0208865Z 
2024-10-16T10:33:49.0209310Z                     VERSION 5.13.2
2024-10-16T10:33:49.0210114Z eslint: v8.57.0
2024-10-16T10:33:49.0210800Z htmlhint: 1.1.4
2024-10-16T10:33:49.0211380Z goreleaser:   ____       ____      _
2024-10-16T10:33:49.0212159Z  / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
2024-10-16T10:33:49.0213041Z | |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
2024-10-16T10:33:49.0213760Z | |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
2024-10-16T10:33:49.0214532Z  \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
2024-10-16T10:33:49.0215533Z goreleaser: Deliver Go Binaries as fast and easily as possible
2024-10-16T10:33:49.0216378Z https://goreleaser.com
2024-10-16T10:33:49.0216844Z 
2024-10-16T10:33:49.0217276Z GitVersion:    2.2.0
2024-10-16T10:33:49.0217908Z GitCommit:     111121bbd98df17cc5d81888aa94a8d3694bc157
2024-10-16T10:33:49.0218978Z GitTreeState:  false
2024-10-16T10:33:49.0219785Z BuildDate:     2024-08-15T01:56:53Z
2024-10-16T10:33:49.0220425Z BuiltBy:       goreleaser
2024-10-16T10:33:49.0221129Z GoVersion:     go1.23.0
2024-10-16T10:33:49.0221696Z Compiler:      gc
2024-10-16T10:33:49.0222496Z ModuleSum:     h1:IKWOpyx4A9gG/8o2AEN46PlV3qR/HqXVTHT6W+G8Qi0=
2024-10-16T10:33:49.0223491Z Platform:      linux/amd64
2024-10-16T10:33:49.0224247Z checkov: 3.2.236
2024-10-16T10:33:49.0225212Z lua: Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
2024-10-16T10:33:49.0226047Z standard: 17.1.0
2024-10-16T10:33:49.0226954Z 2024-10-16 10:33:49 [INFO]   --------------------------------------------
2024-10-16T10:33:49.0228135Z 2024-10-16 10:33:49 [INFO]   Gathering GitHub information...
2024-10-16T10:33:49.0275004Z 2024-10-16 10:33:49 [INFO]   Successfully validated GITHUB_WORKSPACE: /github/workspace
2024-10-16T10:33:49.0845201Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_EVENT_PATH: /github/workflow/event.json]
2024-10-16T10:33:49.1024765Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_SHA: efdc2365d60a89e4a215f5e05076f9a759c70d4c
2024-10-16T10:33:49.1696005Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_PUSH_COMMIT_COUNT: 1
2024-10-16T10:33:49.2362751Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_BEFORE_SHA: 6a948fa4d461976385aa152d7e49799ae1205caf
2024-10-16T10:33:49.2418019Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_ORG: some-team
2024-10-16T10:33:49.2542254Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_REPO: some-product-configuration
2024-10-16T10:33:49.2740256Z 2024-10-16 10:33:49 [INFO]   The default branch for this repository is set to: develop
2024-10-16T10:33:49.2798280Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_TOKEN.
2024-10-16T10:33:49.2853455Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_REPOSITORY: some-team/some-product-configuration
2024-10-16T10:33:49.2910358Z 2024-10-16 10:33:49 [INFO]   Successfully found GITHUB_RUN_ID 10060936
2024-10-16T10:33:49.4025949Z 2024-10-16 10:33:49 [INFO]   --------------------------------------------
2024-10-16T10:33:49.4078879Z 2024-10-16 10:33:49 [INFO]   Validating the configuration
2024-10-16T10:33:51.0814636Z .git
2024-10-16T10:33:51.1567928Z 2024-10-16 10:33:51 [INFO]   The develop branch doesn't exist in /github/workspace
2024-10-16T10:33:51.1699349Z d4848bebc7b5545268f7fb9c7fe63140dd6f02e4
2024-10-16T10:33:51.1804634Z 2024-10-16 10:33:51 [INFO]   develop doesn't exist, however origin/develop exists. Setting DEFAULT_BRANCH to: origin/develop
2024-10-16T10:33:51.9843276Z 2024-10-16 10:33:51 [INFO]   ----------------------------------------------
2024-10-16T10:33:51.9895993Z 2024-10-16 10:33:51 [INFO]   User provided file:[/github/workspace/actionlint.yml] exists, setting rules file...
2024-10-16T10:33:52.9453819Z 2024-10-16 10:33:52 [INFO]   ----------------------------------------------
2024-10-16T10:33:52.9502439Z 2024-10-16 10:33:52 [INFO]   User provided file:[/github/workspace/.markdownlint.yaml] exists, setting rules file...
2024-10-16T10:33:54.5855775Z 2024-10-16 10:33:54 [INFO]   ----------------------------------------------
2024-10-16T10:33:54.5907174Z 2024-10-16 10:33:54 [INFO]   User provided file:[/github/workspace/.yamllint.yaml] exists, setting rules file...
2024-10-16T10:34:02.0122969Z 2024-10-16 10:34:02 [INFO]   Building the list of files and directories to check
2024-10-16T10:34:14.0354059Z 2024-10-16 10:34:14 [INFO]   Successfully gathered list of files...
2024-10-16T10:34:14.0425487Z ##[endgroup]
2024-10-16T10:34:20.1391737Z 2024-10-16 10:34:20 [INFO]   Command output when running linters:
2024-10-16T10:34:20.1392581Z ------
2024-10-16T10:34:20.1393604Z ##[group]GITHUB_ACTIONS
2024-10-16T10:34:20.1394274Z 2024-10-16 10:34:14 [INFO]   Linting GITHUB_ACTIONS items...
2024-10-16T10:34:20.1395294Z 2024-10-16 10:34:14 [NOTICE]   GITHUB_ACTIONS linted successfully
2024-10-16T10:34:20.1396513Z ##[endgroup]
2024-10-16T10:34:20.1397327Z ##[group]JSON
2024-10-16T10:34:20.1398009Z 2024-10-16 10:34:14 [INFO]   Linting JSON items...
2024-10-16T10:34:20.1399004Z 2024-10-16 10:34:19 [ERROR]   Found errors when linting JSON. Exit code: 1.
2024-10-16T10:34:20.1399953Z 2024-10-16 10:34:20 [INFO]   Stderr contents for JSON:
2024-10-16T10:34:20.1400627Z ------
2024-10-16T10:34:20.1400906Z 
2024-10-16T10:34:20.1401183Z Oops! Something went wrong! :(
2024-10-16T10:34:20.1401536Z 
2024-10-16T10:34:20.1401734Z ESLint: 8.57.0
2024-10-16T10:34:20.1401961Z 
2024-10-16T10:34:20.1402654Z Error: Cannot read config file: /github/workspace/packages/config-generator/.eslintrc.cjs
2024-10-16T10:34:20.1403948Z Error: Cannot find module '@rushstack/eslint-patch/modern-module-resolution'
2024-10-16T10:34:20.1404692Z Require stack:
2024-10-16T10:34:20.1405410Z - /github/workspace/packages/config-generator/.eslintrc.cjs
2024-10-16T10:34:20.1406396Z - /node_modules/@eslint/eslintrc/dist/eslintrc.cjs
2024-10-16T10:34:20.1407197Z - /node_modules/eslint/lib/cli-engine/cli-engine.js
2024-10-16T10:34:20.1408633Z - /node_modules/eslint/lib/eslint/eslint.js
2024-10-16T10:34:20.1409374Z - /node_modules/eslint/lib/eslint/index.js
2024-10-16T10:34:20.1410353Z - /node_modules/eslint/lib/cli.js
2024-10-16T10:34:20.1411145Z - /node_modules/eslint/bin/eslint.js
2024-10-16T10:34:20.1412100Z     at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
2024-10-16T10:34:20.1413094Z     at Module._load (node:internal/modules/cjs/loader:983:27)
2024-10-16T10:34:20.1413848Z     at Module.require (node:internal/modules/cjs/loader:1230:19)
2024-10-16T10:34:20.1414569Z     at require (node:internal/modules/helpers:179:18)
2024-10-16T10:34:20.1415559Z     at Object.<anonymous> (/github/workspace/packages/config-generator/.eslintrc.cjs:1:1)
2024-10-16T10:34:20.1416573Z     at Module._compile (node:internal/modules/cjs/loader:1368:14)
2024-10-16T10:34:20.1417705Z     at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
2024-10-16T10:34:20.1418968Z     at Module.load (node:internal/modules/cjs/loader:1205:32)
2024-10-16T10:34:20.1420029Z     at Module._load (node:internal/modules/cjs/loader:1021:12)
2024-10-16T10:34:20.1420931Z     at Module.require (node:internal/modules/cjs/loader:1230:19)
2024-10-16T10:34:20.1421589Z ------
2024-10-16T10:34:20.1422360Z ##[endgroup]
2024-10-16T10:34:20.1423386Z ##[group]MARKDOWN
2024-10-16T10:34:20.1424112Z 2024-10-16 10:34:14 [INFO]   Linting MARKDOWN items...
2024-10-16T10:34:20.1425708Z 2024-10-16 10:34:15 [NOTICE]   MARKDOWN linted successfully
2024-10-16T10:34:20.1426592Z ##[endgroup]
2024-10-16T10:34:20.1427425Z ##[group]YAML
2024-10-16T10:34:20.1427992Z 2024-10-16 10:34:14 [INFO]   Linting YAML items...
2024-10-16T10:34:20.1428778Z 2024-10-16 10:34:15 [NOTICE]   YAML linted successfully
2024-10-16T10:34:20.1429517Z 2024-10-16 10:34:15 [INFO]   Command output for YAML:
2024-10-16T10:34:20.1430094Z ------
2024-10-16T10:34:20.1431175Z /github/workspace/.github/workflows/seamless-release.yml:219:7: [warning] comment not indented like content (comments-indentation)
2024-10-16T10:34:20.1433101Z /github/workspace/.github/workflows/seamless-ci.yml:147:3: [warning] comment not indented like content (comments-indentation)
2024-10-16T10:34:20.1435128Z /github/workspace/.github/workflows/seamless-publish.yml:57:7: [warning] comment not indented like content (comments-indentation)
2024-10-16T10:34:20.1436761Z /github/workspace/.github/workflows/seamless-release-hotfix.yml:256:7: [warning] comment not indented like content (comments-indentation)
2024-10-16T10:34:20.1437935Z ------
2024-10-16T10:34:20.1438813Z ##[endgroup]
2024-10-16T10:34:20.1439212Z ------
2024-10-16T10:34:20.1601001Z 2024-10-16 10:34:20 [INFO]   ----------------------------------------------
2024-10-16T10:34:20.1652199Z 2024-10-16 10:34:20 [INFO]   ----------------------------------------------
2024-10-16T10:34:20.2600488Z 2024-10-16 10:34:20 [NOTICE]   Successfully linted GITHUB_ACTIONS
2024-10-16T10:34:20.5396835Z 2024-10-16 10:34:20 [ERROR]   Errors found in JSON
2024-10-16T10:34:20.7712744Z 2024-10-16 10:34:20 [NOTICE]   Successfully linted MARKDOWN
2024-10-16T10:34:21.8678958Z 2024-10-16 10:34:21 [NOTICE]   Successfully linted YAML
2024-10-16T10:34:22.0438824Z 2024-10-16 10:34:21 [ERROR]   Super-linter detected linting errors
2024-10-16T10:34:22.0446649Z super-linter-output/super-linter-summary.md 47ms
2024-10-16T10:34:22.0607018Z Post job cleanup.
```

### Steps To Reproduce

1. Have an eslintrc config that requires a package that is not bundled with the super-linter
2. Enable the JSON validation
3. Execute the super-linter

**Comment by ferrarimarco** [comment] 2024-10-21 16:37
Hi, thanks for taking the time to report this issue.

This is likely a duplicate of #6089

**Closed by ferrarimarco** 2024-10-21 16:37 UTC
Labels: bug
