### ISSUE TITLE
version pinning needs to be exact?

### ISSUE THREAD

**Issue by zkoppert** [super-linter/super-linter#4650] opened 2023-09-12 18:59 UTC
Isn't that behaviour potentially unexpected? When I pin super-linter/slim to v5.2.2, it'll fetch the slim-v5 image, which is going to be some more recent version than v5.2.2 in the future, no?

_Originally posted by @bewuethr in https://github.com/super-linter/super-linter/issues/4564#issuecomment-1716147164_

**Comment by bewuethr** [comment] 2023-09-12 19:23
I'd argue that it should be exact, or else my builds aren't reproducible, even though I have all dependencies pinned on my end.

**Comment by ferrarimarco** [comment] 2023-09-13 07:57
If you want fully reproducible builds, exact version pinning is the way to go.

**Comment by zkoppert** [comment] 2023-10-17 03:53
Reopening issue as I am reverting the implementation (which never worked). Will need to find a new solution to this that is also compatible with having the merge queue turned on.

**Comment by ferrarimarco** [comment] 2023-12-18 10:19
Closing this one because we'll tackle automated updates as part of the release workflow.

**Closed by ferrarimarco** 2023-12-18 10:19 UTC
Labels: automation, blocked
