### ISSUE TITLE
.gitleaksignore file not taken into account

### ISSUE THREAD

**Issue by JonZeolla** [super-linter/super-linter#3552] opened 2022-11-16 13:27 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is no way for a `.gitleaksignore` file to be taken into account when using the `super-linter`.  More details on how `gitleaks` supports this [here](https://github.com/zricethezav/gitleaks#gitleaksignore).

**Describe the solution you'd like**
It would be great that, if we stored a `.gitleaksignore` file in our repo, that it would be accounted for by `super-linter`'s use of `gitleaks`.

**Describe alternatives you've considered**
It is possible to use a `gitleaks` configuration file to set a global allowlist based on the file (`path`). However, this is a global allowlist, and not as specific as `.gitleaksignore`

**Additional context**
There was an issue for this previously opened in #3407 but that was closed prior to the problem being resolved.  I noted details in that issue, but it is closed and I'm unable to reopen it.

https://github.com/github/super-linter/issues/3552#tasklist-block-37ec27ec-288a-49bd-b71b-5c3334363b9d

**Comment by thomasleplus** [comment] 2022-12-06 18:55
Hi,

I am facing the same issue and I've tried placing my .gitleaksignore file at the root of my repo as well as in `.github/linters/` but neither worked. [leplusorg/openid-connect-provider-debugger](https://github.com/leplusorg/openid-connect-provider-debugger) is the repo that I'm trying to configure it is helps (and the corresponding workflow is [here](https://github.com/leplusorg/openid-connect-provider-debugger/actions/workflows/linter.yml)).

Thanks,

Tom

**Comment by thomasleplus** [comment] 2023-04-16 20:23
Just an update to confirm that the issue is not resolved in version 5. Cheers

**Comment by joshunger** [comment] 2023-10-27 17:22
@JonZeolla @thomasleplus I just added a `.gitleaksignore` at the root and it is working for me. Maybe something changed recently. Is it working for you two?

**Comment by JonZeolla** [comment] 2023-10-27 17:58
I'm not sure, we stopped using super-linter

**Comment by thomasleplus** [comment] 2023-10-27 18:13
I have tried moving my `.gitleaksignore` file at the root of my repo but I am still having the issue. So I moved it back to the `.github/linters/` for now. But you're comment prompted me look at my `.gitleaksignore` file again and I noticed something that may be relevant: I have 3 ignore instructions in my `gitleaksignore` [file](https://github.com/leplusorg/openid-connect-provider-debugger/blob/main/.github/linters/.gitleaksignore) and one instruction seems to be working for README.md at the root of my project. The other two are in a subdirectory so maybe the issue only happens for files in subdirectories.

I took the 2 entries in my `.gitleaksignore` file straight from super-linter's log in my workflow action (specifically the `Fingerprint:` messages):

```
2023-10-27 18:07:02 [INFO]   File:[/github/workspace/openid-connect-provider-debugger/docker-compose.test.yml]
2023-10-27 18:07:02 [ERROR]   Found errors in [gitleaks] linter!
2023-10-27 18:07:02 [ERROR]   Error code: 1. Command output:
------
Finding:     - oidc_client_id=kbyuFDidLLm280LIwVFiazOqjO3ty8KH
    - oidc_client_s...
Secret:      kbyuFDidLLm280LIwVFiazOqjO3ty8KH
RuleID:      generic-api-key
Entropy:     4.538910
File:        /github/workspace/openid-connect-provider-debugger/docker-compose.test.yml
Line:        16
Fingerprint: /github/workspace/openid-connect-provider-debugger/docker-compose.test.yml:generic-api-key:16

Finding:     - oidc_client_secret=60Op4HFM0I8ajz0WdiStAbziZ-VFQttXuxixHHs2R7r7-CW8GR79l-mmLqMhc-Sa
    - oidc_discover...
Secret:      60Op4HFM0I8ajz0WdiStAbziZ-VFQttXuxixHHs2R7r7-CW8GR79l-mmLqMhc-Sa
RuleID:      generic-api-key
Entropy:     5.191024
File:        /github/workspace/openid-connect-provider-debugger/docker-compose.test.yml
Line:        17
Fingerprint: /github/workspace/openid-connect-provider-debugger/docker-compose.test.yml:generic-api-key:17
```

**Comment by ferrarimarco** [comment] 2023-11-27 10:59
This looks like a configuration issue. I would suggest asking in the gitleaks repository for support to handle your particular case.

**Closed by ferrarimarco** 2023-11-27 10:59 UTC
Labels: enhancement, O: backlog 🤖

**Comment by joshunger** [comment] 2023-11-27 15:06
@thomasleplus we have only used it for several files at the root of our project

**Comment by thomasleplus** [comment] 2023-11-27 19:51
Can you confirm if super-linter expects the .gitleaksignore config file at the root of the repo or inside the .github/linters/ subdirectory? Or does super-linter just let gitleaks find its config file on its own with no interference?

Once I know I have my config file in the right place, I can focus my investigation on its content.

Thanks

**Comment by ferrarimarco** [comment] 2023-11-29 13:06
Hi there! There's nothing specific about `.gitleaksignore` in super-linter, so we don't assume anything about that file.

**Comment by joshunger** [comment] 2023-11-29 18:39
@thomasleplus we have ours at the root of the repo
