### ISSUE TITLE
Option to disable use of git while linting

### ISSUE THREAD

**Issue by rmatte** [super-linter/super-linter#4951] opened 2023-12-06 16:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

super-linter always tries to use git when linting. We don't use git but we do use super-linter in many places to do linting. Because of the recent changes in https://github.com/super-linter/super-linter/pull/4889 our linting is totally busted now because we just end up with "[FATAL]   /tmp/lint is not a Git repository." and it exits out and doesn't perform the linting. Prior to that change it would just continue and work as expected.

### Expected Behavior

There should be an option to just skip around the git stuff and run the linters on the code in the directory. Not everyone who is using this is necessarily using git for their version control. This is a great linter and it would be nice if it were more generally applicable. Thanks.

**Comment by rmatte** [comment] 2023-12-06 17:42
I found something interesting while looking in to this. It seems that the intention is to allow us to skip over the new git validations if USE_FIND_ALGORITHM=true but in the lib/linter.sh file it has...

```
if [[ "${USE_FIND_ALGORITHM}" != "false" ]] || [[ "${VALIDATE_ALL_CODEBASE}" != "true" ]]; then
  debug "Validate the local Git environment"
  ValidateLocalGitRepository
  ValidateGitShaReference
  ValidateDefaultGitBranch
else
  debug "Skipped the validation of the local Git environment because we don't depend on it."
fi
```

USE_FIND_ALGORITHM=true is supposed to use the Linux "find" command instead of "git diff" so I'm fairly certain that what they intended for that if statement is actually...

```
if [[ "${USE_FIND_ALGORITHM}" != "true" ]] || [[ "${VALIDATE_ALL_CODEBASE}" != "true" ]]; then
```

That way we could just enable USE_FIND_ALGORITHM to tell it to use find instead of git and work around this issue.

**Comment by ferrarimarco** [comment] 2023-12-06 17:43
Hi @rmatte !

This looks like a duplicate of #4952

**Closed by ferrarimarco** 2023-12-06 17:43 UTC
Labels: enhancement
